<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="images\Babbage.jpg" />
	  <Content Include="images\Berners-Lee.jpg" />
	  <Content Include="images\Chomsky.jpg" />
	  <Content Include="images\Codd.jpg" />
	  <Content Include="images\diamond.png" />
	  <Content Include="images\Dijkstra.jpg" />
	  <Content Include="images\Einstein.jpg" />
	  <Content Include="images\Ershov.jpg" />
	  <Content Include="images\Huntington.jpg" />
	  <Content Include="images\Knuth.jpg" />
	  <Content Include="images\Linus.jpg" />
	  <Content Include="images\Lovelace.jpg" />
	  <Content Include="images\Neumann.jpg" />
	  <Content Include="images\Tanenbaum.jpg" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\6\ASPA\DAL_Celebrity_MSSQL\DAL_Celebrity_MSSQL.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="images\" />
	</ItemGroup>

</Project>
